#!/bin/bash

deepspeed --include localhost:2,3 llava/train/train_mem.py \
    --deepspeed ../DS/zero2.json \
    --model_name_or_path ../Model/Llama3-8B-R1 \
    --version plain \
    --data_path ../Data/CholecT45/data/jsons/pt_merged_with_video.json \
    --image_folder ../Data/CholecT45/data/Data_PNGs \
    --vision_tower mamba \
    --mm_projector_type mamba2x \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-cholecmamba-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 24000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
